package io.github.tieo.phonetix.core

// The accents each language offers.
//
// Generated by tools/gen_types.py from data/accents.json; edit that and run it
// again. An accent is offered only where there is a voice that really exists or a
// rule that holds for a whole vocabulary.

data class Accent(
    val id: String,
    val name: String,
    /** The espeak voice, which is what says a word nothing has a recording of. */
    val voice: String,
    /** Whether the core rewrites a standard transcription into this accent. */
    val rule: Boolean,
)

object Accents {

    val all: Map<String, List<Accent>> = mapOf(
        "de" to listOf(Accent("de", "Germany", "de", false), Accent("de-ch", "Switzerland", "de", true), Accent("de-at", "Austria", "de", true)),
        "en" to listOf(Accent("en-gb", "British", "en-gb-x-rp", false), Accent("en-us", "American", "en-us", true), Accent("en-gb-scotland", "Scottish", "en-gb-scotland", false), Accent("en-au", "Australian", "en-au", false), Accent("en-029", "Caribbean", "en-029", false), Accent("en-ca", "Canadian", "en-us", true)),
        "es" to listOf(Accent("es", "Spain", "es", false), Accent("es-419", "Latin America", "es-419", true), Accent("es-ar", "Rioplatense", "es-419", true)),
        "fr" to listOf(Accent("fr", "France", "fr", false), Accent("fr-ca", "Canada", "fr-ca", false)),
        "pt" to listOf(Accent("pt", "Portugal", "pt", false), Accent("pt-br", "Brazil", "pt-br", false)),
        "vi" to listOf(Accent("vi", "Northern", "vi", false), Accent("vi-vn-x-central", "Central", "vi-vn-x-central", false)),
    )

    /** What a language offers, which is nothing for most of them. */
    fun of(lang: String): List<Accent> = all[lang] ?: emptyList()

    /** The voice that says a word in this accent, or the language's own. */
    fun voiceOf(lang: String, accent: String): String =
        of(lang).firstOrNull { it.id == accent }?.voice ?: lang
}
