package io.github.tieo.phonetix.core

// The accents each language offers.
//
// Generated by tools/gen_types.py from data/accents.json; edit that and run it
// again. An accent is offered only where there is a voice that really exists or a
// rule that holds for a whole vocabulary.

data class Accent(
    val id: String,
    val name: String,
    /** The name cut to what a chip beside a transcription holds: the region's code. */
    val short: String,
    /** The espeak voice, which is what says a word nothing has a recording of. */
    val voice: String,
    /** Whether the core rewrites a standard transcription into this accent. */
    val rule: Boolean,
)

object Accents {

    val all: Map<String, List<Accent>> = mapOf(
        "de" to listOf(Accent("de", "Germany", "DE", "de", false), Accent("de-ch", "Switzerland", "CH", "de", true), Accent("de-at", "Austria", "AT", "de", true)),
        "en" to listOf(Accent("en-gb", "British", "GB", "en-gb-x-rp", true), Accent("en-us", "American", "US", "en-us", true), Accent("en-gb-scotland", "Scottish", "SCOT", "en-gb-scotland", false), Accent("en-au", "Australian", "AU", "en-au", false), Accent("en-029", "Caribbean", "CARIB", "en-029", false), Accent("en-ca", "Canadian", "CA", "en-us", true)),
        "es" to listOf(Accent("es", "Spain", "ES", "es", false), Accent("es-419", "Latin America", "LATAM", "es-419", true), Accent("es-ar", "Rioplatense", "AR", "es-419", true)),
        "fr" to listOf(Accent("fr", "France", "FR", "fr", false), Accent("fr-ca", "Canada", "CA", "fr-ca", false)),
        "pt" to listOf(Accent("pt-pt", "Portugal", "PT", "pt", false), Accent("pt-br", "Brazil", "BR", "pt-br", false)),
        "vi" to listOf(Accent("vi", "Northern", "North", "vi", false), Accent("vi-vn-x-central", "Central", "Central", "vi-vn-x-central", false)),
    )

    /** What a language offers, which is nothing for most of them. */
    fun of(lang: String): List<Accent> = all[lang] ?: emptyList()

    /** The voice that says a word in this accent, or the language's own. */
    fun voiceOf(lang: String, accent: String): String =
        of(lang).firstOrNull { it.id == accent }?.voice ?: lang

    /** The accent a language is read in until the reader picks another, or nothing for
     *  a language with no accents to choose between. */
    fun defaultOf(lang: String): String = DEFAULTS[lang] ?: ""

    private val DEFAULTS: Map<String, String> = mapOf(
        "de" to "de",
        "en" to "en-us",
        "es" to "es",
        "fr" to "fr",
        "pt" to "pt-br",
        "vi" to "vi",
    )
}
