package io.github.tieo.phonetix.core

/**
 * Whether a piece of text is in the language the dictionary is for.
 *
 * There is one dictionary here, English, and until now every word on the screen was looked up
 * in it. That put English pronunciations through German sentences: a reader in Germany got
 * them on "Song" and "Video", and on "war", "hat" and "man", which are German words that
 * happen to be spelled like English ones.
 *
 * Coverage against the dictionary cannot answer this, the way it does in the extension. That
 * dictionary is built from Wiktionary and holds the words of one language; this one is
 * generated by espeak, which will pronounce any string of letters, so "und", "der" and "das"
 * are all in it - with English vowels. Asked how much of a German sentence it explains, it
 * says three quarters.
 *
 * What can answer it is already in the app: the three hundred commonest words of each of
 * thirty-eight languages, shipped for the sprinkle. Function words are what a language uses
 * most and what it shares least, so the language whose commonest words appear in a line is
 * the language of the line. It is the same question the extension asks - whose data explains
 * this text - put to the data that can answer it here.
 *
 * A line too short to hold a function word is answered for by the screen it is on, which is
 * the page language standing in as the prior for a block too short to judge.
 */
object Language {

    /** What a text says about its own language: how many of the words are the commonest
     *  words of English, how many are another language's, and which language that was. */
    class Reading(val english: Int, val other: Int, val otherIs: String?, val words: Int) {

        /** Too little in it was any language's common word for it to answer for itself.
         *
         *  One word is not evidence: "Video" is among the commonest words of Italian and not
         *  of English, so a single hit had a tab labelled Video declaring itself Italian on
         *  an English page and going untranscribed. Two independent hits, or none. */
        val silent: Boolean get() = english + other < SPEAKS_UP

        operator fun plus(that: Reading): Reading {
            // The louder of the two voices keeps the name: adding a line of German to a line
            // of French should not produce a screen that is neither.
            val (name, count) = if (that.other > other) that.otherIs to that.other
            else otherIs to other
            return Reading(english + that.english, count, name, words + that.words)
        }
    }

    val nothing = Reading(0, 0, null, 0)

    fun read(text: CharSequence): Reading {
        var english = 0
        val hits = HashMap<String, Int>(4)
        var words = 0
        Transcriber.scanWords(text) { i, j ->
            if (j - i >= MIN_WORD) {
                words++
                val word = text.subSequence(i, j).toString().lowercase()
                for (lang in Dictionary.speaks(word)) {
                    if (lang == "en") english++ else hits[lang] = (hits[lang] ?: 0) + 1
                }
            }
        }
        val top = hits.maxByOrNull { it.value }
        return Reading(english, top?.value ?: 0, top?.key, words)
    }

    /**
     * Whether this line is worth transcribing at all.
     *
     * @param line what this line alone says about itself
     * @param screen what every line on this screen says together
     */
    fun ours(line: Reading, screen: Reading): Boolean {
        if (line.words == 0) return false
        // A line that speaks for itself is taken at its word, whatever the screen around it
        // is. An English title on a German page is still English, and suppressing it for its
        // surroundings would be the same mistake pointing the other way.
        if (!line.silent) return line.english * 2 >= line.other
        // It said nothing about itself: a tab, a button, a heading of one or two words. Then
        // the screen answers for it, and where the screen said nothing either, the words are
        // transcribed as they always were.
        if (screen.silent) return true
        return screen.english * 2 >= screen.other
    }

    /** Shorter than this is not a word for these purposes, matching what is transcribed. */
    const val MIN_WORD = 2

    /** How many of a text's words have to be some language's commonest before the text is
     *  allowed to answer for its own language rather than the screen answering for it. */
    const val SPEAKS_UP = 2
}
