package io.github.tieo.phonetix.core

/**
 * Whether a piece of text is in the language the dictionary is for.
 *
 * There is one dictionary here, English, and until now every word on the screen was looked up
 * in it. That put English pronunciations through German sentences: a reader in Germany got them
 * on "Song" and "Video", and on "war", "hat" and "man", which are German words that happen to
 * be spelled like English ones.
 *
 * Coverage against the dictionary cannot answer this the way it does in the extension. That
 * dictionary is built from Wiktionary and holds the words of one language; this one is
 * generated by espeak, which will pronounce any string of letters, so "und", "der" and "das"
 * are all in it - with English vowels. Asked how much of a German sentence it explains, it says
 * three quarters.
 *
 * So the extension's own detector answers it: [Eld], ported, model and all. What eld cannot
 * answer is a line of one or two words - it says so itself, and a tab labelled "Video" is
 * Italian as far as any ngram is concerned - and there the screen the line is on answers for
 * it, which is what the extension does with the page's language.
 */
object Language {

    /** What a text says about its own language. */
    class Reading(
        /** What it was found to be, when that finding was worth anything. */
        val language: String?,
        /** How many words it had, so a screen can weigh its lines. */
        val words: Int,
    ) {
        val silent: Boolean get() = language == null

        /** Two readings together, which is how a screen is read: the language of the most
         *  text on it. */
        operator fun plus(that: Reading): Reading = when {
            that.language == null -> Reading(language, words + that.words)
            language == null -> Reading(that.language, words + that.words)
            language == that.language -> Reading(language, words + that.words)
            // Two languages on one screen, which is ordinary - a German page quoting an
            // English title. The one with more of the screen carries it.
            that.words > words -> Reading(that.language, words + that.words)
            else -> Reading(language, words + that.words)
        }
    }

    val nothing = Reading(null, 0)

    fun read(text: CharSequence): Reading {
        var words = 0
        Transcriber.scanWords(text) { i, j -> if (j - i >= MIN_WORD) words++ }
        if (words == 0) return Reading(null, 0)
        val guess = Eld.detect(text)
        return Reading(if (guess.reliable) guess.language else null, words)
    }

    /**
     * Whether this line is worth transcribing at all.
     *
     * @param line what this line alone says about itself
     * @param screen what every line on this screen says together
     */
    fun ours(line: Reading, screen: Reading): Boolean {
        if (line.words == 0) return false
        // A line that speaks for itself is taken at its word, whatever the screen around it
        // is. An English title on a German page is still English, and suppressing it for its
        // surroundings would be the same mistake pointing the other way.
        if (!line.silent) return line.language == OURS
        // It said nothing about itself: a tab, a button, a heading of one or two words. Then
        // the screen answers for it, and where the screen said nothing either, the words are
        // transcribed as they always were - which is what this did everywhere before it could
        // tell one language from another.
        if (screen.silent) return true
        return screen.language == OURS
    }

    /** The language the dictionary is for. */
    const val OURS = "en"

    /** Shorter than this is not a word for these purposes, matching what is transcribed. */
    const val MIN_WORD = 2
}
