package io.github.tieo.phonetix.core

/**
 * What each language is called.
 *
 * Generated by tools/gen_types.py from data/languages.json; edit that and run it
 * again. A code the table does not hold is shown as the code: inventing a name for a
 * language is worse than admitting the table is short.
 */
object Languages {

    data class Named(val english: String, val native: String, val rtl: Boolean)

    private val TABLE: Map<String, Named> = mapOf(
        "ar" to Named("Arabic", "العربية", true),
        "cs" to Named("Czech", "čeština", false),
        "da" to Named("Danish", "dansk", false),
        "de" to Named("German", "Deutsch", false),
        "el" to Named("Greek", "Ελληνικά", false),
        "en" to Named("English", "English", false),
        "es" to Named("Spanish", "español", false),
        "fa" to Named("Persian", "فارسی", true),
        "fi" to Named("Finnish", "suomi", false),
        "fr" to Named("French", "français", false),
        "he" to Named("Hebrew", "עברית", true),
        "hi" to Named("Hindi", "हिन्दी", false),
        "hu" to Named("Hungarian", "magyar", false),
        "id" to Named("Indonesian", "Bahasa Indonesia", false),
        "it" to Named("Italian", "italiano", false),
        "ja" to Named("Japanese", "日本語", false),
        "ko" to Named("Korean", "한국어", false),
        "nl" to Named("Dutch", "Nederlands", false),
        "no" to Named("Norwegian", "norsk", false),
        "pl" to Named("Polish", "polski", false),
        "pt" to Named("Portuguese", "português", false),
        "ro" to Named("Romanian", "română", false),
        "ru" to Named("Russian", "русский", false),
        "sv" to Named("Swedish", "svenska", false),
        "th" to Named("Thai", "ไทย", false),
        "tr" to Named("Turkish", "Türkçe", false),
        "uk" to Named("Ukrainian", "українська", false),
        "vi" to Named("Vietnamese", "Tiếng Việt", false),
        "zh" to Named("Chinese", "中文", false),
    )

    /** What to call this language to a reader, or the code when it is not named. */
    fun english(code: String): String = TABLE[code.lowercase()]?.english ?: code

    /** What its own speakers call it. */
    fun native(code: String): String = TABLE[code.lowercase()]?.native ?: code

    /** Whether it is written right to left, which decides how a card lays a line out. */
    fun rtl(code: String): Boolean = TABLE[code.lowercase()]?.rtl ?: false

    /** Every language the interface can name. */
    fun all(): List<String> = TABLE.keys.sorted()
}
