package io.github.tieo.phonetix.core

/**
 * The words the settings surfaces are made of.
 *
 * Generated by tools/gen_types.py from data/wording.json; edit that and run it again.
 * A choice this surface cannot draw is not offered here: an overlay paints over what an
 * app has already drawn, so there is no room above a word for a second line and the chip
 * over it is itself the replacement.
 *
 * Both platforms say them: a row named one thing here and another in the extension is
 * one product speaking with two voices, and a one-word label is only a choice for
 * somebody who already knows what the other options are.
 */
data class Choice(val value: String, val label: String, val about: String)

/** What one row is called, and what it says under its name. */
data class Words(val name: String, val about: String)

object Wording {
    /** Transcriptions, as an overlay can draw them. */
    val detail = listOf(
        Choice("broad", "Broad", "the sounds that tell words apart"),
        Choice("narrow", "Narrow", "every detail of how it is said, like aspiration and devoicing"),
    )

    /** Show over a word, as an overlay can draw them. */
    val layer = listOf(
        Choice("off", "Nothing", "the screen as it is; the circle when you want a word"),
        Choice("gloss", "What it means", "the meaning, over the word"),
        Choice("ipa", "How it is said", "the pronunciation, over the word"),
    )

    /** Every row of the settings surfaces, by the name it reports itself under. */
    val rows = mapOf(
        "accent" to Words("Accent", "which accent each language is read in"),
        "animations" to Words("Animations", "the card eases in; off is instant"),
        "delay" to Words("Rest before a card opens", "how long the cursor stays on a word before it answers"),
        "density" to Words("How often", "how much of the page is annotated"),
        "dictionaries" to Words("Dictionaries", "the words this can answer without asking anyone"),
        "host" to Words("Where they come from", "Fetched once and kept on this machine, so a dictionary works on a train."),
        "layer" to Words("Show over a word", ""),
        "more" to Words("How it reads", "transcriptions, stress, how long a rest opens a card"),
        "narrow" to Words("Transcriptions", ""),
        "on" to Words("Annotate what I read", ""),
        "site" to Words("On this site", "the default is what happens on sites you have not decided about"),
        "source" to Words("This page is in", "Each block is read on its own, so a page in two languages already reads correctly. Set this only where that goes wrong."),
        "stress" to Words("Stress marks", "over a word; the card always shows them"),
        "target" to Words("I read into", "the language the answers come in"),
    )

    /** What the two ends of a bar mean. */
    val ends = mapOf(
        "delay" to Pair("instant", "1000 ms"),
        "density" to Pair("a few words", "every word"),
    )

    /** Phrases both surfaces use, so neither invents its own wording. */
    val says = mapOf(
        "dictionary-accent" to "as the dictionary gives it",
        "no-host" to "Nothing is fetched until this is set.",
        "no-source" to "no source for them yet",
        "nothing-yet" to "nothing yet",
    )

    /** What one row is called, or the name it is asked for when the table is short. */
    fun row(name: String): Words = rows[name] ?: Words(name, "")

    /** What one choice is called, for a row that says what it is set to. */
    fun labelOf(choices: List<Choice>, value: String): String =
        choices.firstOrNull { it.value == value }?.label ?: value

    /** What one choice does, for a row that explains itself. */
    fun aboutOf(choices: List<Choice>, value: String): String =
        choices.firstOrNull { it.value == value }?.about ?: ""
}
