package io.github.tieo.phonetix.core

/**
 * The words the settings surfaces are made of.
 *
 * Generated by tools/gen_types.py from data/wording.json; edit that and run it again.
 * A choice this surface cannot draw is not offered here: an overlay paints over what an
 * app has already drawn, so there is no room above a word for a second line and the chip
 * over it is itself the replacement.
 *
 * Both platforms say them: a row named one thing here and another in the extension is
 * one product speaking with two voices, and a one-word label is only a choice for
 * somebody who already knows what the other options are.
 */
data class Choice(val value: String, val label: String, val about: String)

/** What one row is called, and what it says under its name. */
data class Words(val name: String, val about: String)

object Wording {
    /** Transcriptions, as an overlay can draw them. */
    val detail = listOf(
        Choice("broad", "Broad", "the sounds that tell words apart"),
        Choice("narrow", "Narrow", "every detail of how it is said, like aspiration and devoicing"),
    )

    /** Show over a word, as an overlay can draw them. */
    val layer = listOf(
        Choice("off", "Nothing", "the screen as it is; the mark when you want a word"),
        Choice("gloss", "What it means", "the meaning, over the word"),
        Choice("ipa", "How it is said", "the pronunciation, over the word"),
    )

    /** Every row of the settings surfaces, by the name it reports itself under. */
    val rows = mapOf(
        "accent" to Words("Accent", "which accent each language is read in"),
        "animations" to Words("Animations", "the card eases in; off is instant"),
        "apps" to Words("Apps", ""),
        "delay" to Words("Rest before a card opens", "how long the cursor stays on a word before it answers"),
        "density" to Words("How often", "how much of the page is annotated"),
        "dictionaries" to Words("Dictionaries", "the words this can answer without asking anyone"),
        "host" to Words("Where they come from", "Fetched once and kept on this machine, so a dictionary works on a train."),
        "layer" to Words("Show over a word", ""),
        "lens" to Words("The mark", "One mark at the edge of the screen, and the three things it answers"),
        "lens-drag" to Words("Drag it over a word", "It says what it passes over and takes none of the screen's touches"),
        "lens-hold" to Words("Hold it, then sweep", "Every word it passes over joins the run, and the card answers the whole clause"),
        "lens-tap" to Words("Press it", "The whole screen in your own language; press it again to put the screen back"),
        "meanings" to Words("To see what a word means", "How a word is said works already, out of the bundled dictionary. What a word means needs a language to read into and a dictionary for the language you read."),
        "more" to Words("How it reads", "transcriptions, stress, how long a rest opens a card"),
        "narrow" to Words("Transcriptions", ""),
        "on" to Words("Annotate what I read", ""),
        "say" to Words("The word for something", "Type it in your own language and get the word for it, with its entry, so you can judge what a machine gave you."),
        "setup" to Words("Setup", ""),
        "setup-overlay" to Words("Drawing over apps", "Lets it paint the transcription on top of the word."),
        "setup-reading" to Words("Reading the screen", "Lets Phonetix see the words in other apps. Nothing leaves your device."),
        "site" to Words("On this site", "the default is what happens on sites you have not decided about"),
        "source" to Words("This page is in", "Each block is read on its own, so a page in two languages already reads correctly. Set this only where that goes wrong."),
        "start" to Words("Before it can answer a word", "Asked once. Nothing else appears until they are done."),
        "stress" to Words("Stress marks", "over a word; the card always shows them"),
        "target" to Words("I read into", "the language the answers come in"),
        "touch" to Words("Touching a word", ""),
        "touch-words" to Words("Hold a word for its card", ""),
        "where" to Words("Where", ""),
    )

    /** What the two ends of a bar mean. */
    val ends = mapOf(
        "delay" to Pair("instant", "1000 ms"),
        "density" to Pair("a few words", "every word"),
    )

    /** Phrases both surfaces use, so neither invents its own wording. */
    val says = mapOf(
        "allow-overlay" to "Allow overlay",
        "change" to "Change",
        "dictionary-accent" to "as the dictionary gives it",
        "every-app" to "Every app",
        "get" to "Get",
        "loading-dictionary" to "Loading the dictionary…",
        "master-idle" to "Nothing is drawn over your apps",
        "master-off" to "Paused",
        "master-on" to "Reading",
        "master-unready" to "Finish the steps below to switch on",
        "master-working" to "The words in your apps are being answered",
        "no-host" to "Nothing is fetched until this is set.",
        "no-source" to "no source for them yet",
        "nothing-yet" to "nothing yet",
        "open-accessibility" to "Open accessibility",
        "preview" to "Preview",
        "preview-about" to "the words on a page this would answer",
        "remove" to "Remove",
        "say-no-language" to "Choose a language to read into first.",
        "say-no-model" to "No translation model for that direction at your dictionary host.",
        "say-nothing" to "no word for that",
        "say-placeholder" to "what you want to say",
        "start-done" to "done",
        "start-go" to "Set this",
        "start-host" to "Say where your dictionaries come from",
        "start-pack" to "Get a dictionary for the language you are reading",
        "start-permission" to "Let it read the screen, and draw over it",
        "start-target" to "Choose the language you read into",
        "tagline" to "What the words you read mean, and how they are said",
        "touch-off" to "Every touch goes to the app underneath, so scrolling is untouched. Turn this on to open a word's card by holding it.",
        "touch-on" to "Hold a transcription to open its card. While this is on, a swipe that starts on a transcription will not scroll the page.",
        "use-this" to "Use this",
    )

    /** What one row is called, or the name it is asked for when the table is short. */
    fun row(name: String): Words = rows[name] ?: Words(name, "")

    /** What one choice is called, for a row that says what it is set to. */
    fun labelOf(choices: List<Choice>, value: String): String =
        choices.firstOrNull { it.value == value }?.label ?: value

    /** What one choice does, for a row that explains itself. */
    fun aboutOf(choices: List<Choice>, value: String): String =
        choices.firstOrNull { it.value == value }?.about ?: ""
}
