package io.github.tieo.phonetix.core

/**
 * The words the settings surfaces are made of.
 *
 * Generated by tools/gen_types.py from data/wording.json; edit that and run it again.
 * A choice this surface cannot draw is not offered here: an overlay paints over what an
 * app has already drawn, so there is no room above a word for a second line and the chip
 * over it is itself the replacement.
 *
 * Both platforms say them: a row named one thing here and another in the extension is
 * one product speaking with two voices, and a one-word label is only a choice for
 * somebody who already knows what the other options are.
 */
data class Choice(val value: String, val label: String, val about: String)

/** What one row is called, and what it says under its name. */
data class Words(val name: String, val about: String)

object Wording {
    /** Light or dark, as an overlay can draw them. */
    val dark = listOf(
        Choice("system", "System", "whatever this device is set to"),
        Choice("light", "Light", "always the light side of the palette"),
        Choice("dark", "Dark", "always the dark side of the palette"),
    )

    /** Transcriptions, as an overlay can draw them. */
    val detail = listOf(
        Choice("broad", "/ /", "the sounds that tell words apart"),
        Choice("narrow", "[ ]", "every detail of how it is said, like aspiration and devoicing"),
    )

    /** Overlay, as an overlay can draw them. */
    val layer = listOf(
        Choice("off", "Off", "nothing is replaced; the button still answers a word"),
        Choice("meaning", "Translation", "the word replaced by what it means"),
        Choice("sound", "Pronunciation", "the word replaced by how it is said"),
        Choice("both", "Both", "what it means, and how to say that"),
    )

    /** Which side, as an overlay can draw them. */
    val side = listOf(
        Choice("left", "Left", "for a phone held in the left hand"),
        Choice("free", "Anywhere", "it stays wherever you put it down"),
        Choice("right", "Right", "for a phone held in the right hand"),
    )

    /** Every row of the settings surfaces, by the name it reports itself under. */
    val rows = mapOf(
        "accent" to Words("Accent", ""),
        "advanced" to Words("Advanced", ""),
        "animations" to Words("Animations", ""),
        "apps" to Words("Apps", ""),
        "dark" to Words("Light or dark", ""),
        "delay" to Words("Rest before a card opens", ""),
        "density" to Words("How often", ""),
        "dictionaries" to Words("Dictionaries", ""),
        "ipa" to Words("Pronunciation", ""),
        "layer" to Words("Overlay", ""),
        "lens-drag" to Words("Drag it over a word", "It says what it passes over, and the page under it still scrolls"),
        "lens-hold" to Words("Hold it", "Turns the overlay off, and on again; the button wears the accent colour while the overlay is on"),
        "lens-sweep" to Words("Hold it, then sweep", "Every word it passes over joins the run, and the card answers the whole clause"),
        "lens-tap" to Words("Tap it", "Ask for the word for something, in the middle of what you are reading; tap it again to put the card away"),
        "meanings" to Words("To see what a word means", ""),
        "narrow" to Words("Transcriptions", ""),
        "on" to Words("Annotate what I read", ""),
        "rest" to Words("Where the button sits", ""),
        "rest-pin" to Words("Pin", ""),
        "say" to Words("The word for something", ""),
        "setup" to Words("Setup", ""),
        "setup-overlay" to Words("Drawing over apps", ""),
        "setup-reading" to Words("Reading the screen", ""),
        "side" to Words("Which side", ""),
        "site" to Words("On this site", ""),
        "source" to Words("This page is in", ""),
        "start" to Words("Before it can answer a word", ""),
        "stress" to Words("Stress marks", ""),
        "target" to Words("Language", ""),
        "theme" to Words("Theme", ""),
        "touch" to Words("Touching a word", ""),
        "touch-words" to Words("Tap a word for its card", ""),
        "translate" to Words("Translation", ""),
        "where" to Words("Where", ""),
    )

    /** What the two ends of a bar mean. */
    val ends = mapOf(
        "delay" to Pair("instant", "1000 ms"),
        "density" to Pair("a few words", "every word"),
    )

    /** Phrases both surfaces use, so neither invents its own wording. */
    val says = mapOf(
        "allow" to "Allow",
        "allow-overlay" to "Allow overlay",
        "already-in" to "This page is already in %s",
        "broad-mark" to "/ /",
        "change" to "Change",
        "choose-language" to "Choose a language",
        "close" to "Close",
        "detail-explained" to "Broad is the sounds that tell words apart; narrow is every detail of how one is said, as a speaker of that accent says it.",
        "dictionary-accent" to "as the dictionary gives it",
        "every-app" to "Every app",
        "get" to "Get",
        "loading-dictionary" to "Loading the dictionary…",
        "master-idle" to "Nothing is drawn over your apps",
        "master-off" to "Paused",
        "master-on" to "Reading",
        "master-unready" to "Allow it to read the screen and draw over your apps",
        "master-working" to "The words in your apps are being answered",
        "narrow-mark" to "[ ]",
        "no-direction" to "No dictionary here for %s, so words cannot be turned into it. The words show how they sound instead.",
        "no-source" to "for what a word means; how it is said is built in",
        "no-translation" to "Don't translate",
        "nothing-found" to "Nothing by that name",
        "nothing-yet" to "nothing yet",
        "open-accessibility" to "Open accessibility",
        "preview" to "Preview",
        "preview-about" to "the words on a page this would answer",
        "remove" to "Remove",
        "replacing-off" to "Overlay off",
        "replacing-on" to "Overlay on",
        "rest-edge" to "On the %s",
        "rest-loose" to "Wherever you leave it",
        "rest-put" to "Drag the button up or down, or across to the other side.",
        "say-fetching" to "getting what this pair needs, once",
        "say-into" to "Answer in",
        "say-no-language" to "Choose a language to read into first.",
        "say-no-model" to "No translation model for that direction at your dictionary host.",
        "say-nothing" to "no word for that",
        "say-placeholder" to "what you want to say",
        "search" to "Search",
        "service-stopped" to "Phonetix is allowed to read the screen but is not running. Switch it off and on again in the phone's accessibility settings.",
        "start-done" to "done",
        "start-go" to "Set this",
        "start-pack" to "Get a dictionary for the language you are reading",
        "start-permission" to "Let it read the screen, and draw over it",
        "start-target" to "Choose the language you read into",
        "touch-off" to "Every touch goes to the app underneath, so scrolling is untouched.",
        "touch-on" to "A swipe that starts on a word will not scroll the page.",
        "use-this" to "Use this",
    )

    /** What one row is called, or the name it is asked for when the table is short. */
    fun row(name: String): Words = rows[name] ?: Words(name, "")

    /** What one choice is called, for a row that says what it is set to. */
    fun labelOf(choices: List<Choice>, value: String): String =
        choices.firstOrNull { it.value == value }?.label ?: value

    /** What one choice does, for a row that explains itself. */
    fun aboutOf(choices: List<Choice>, value: String): String =
        choices.firstOrNull { it.value == value }?.about ?: ""
}
