// Which side of itself each palette carries.
//
// Generated by tools/gen_types.py from docs/merge/surface.html; edit that and run
// it again.

export const SIDES: Record<string, string[]> = {
  classroom: ['dark', 'light'],
  dracula: ['dark'],
  ink: ['dark', 'light'],
  nord: ['light'],
  paper: ['dark', 'light'],
  phonetix: ['dark', 'light'],
  silk: ['light'],
  winter: ['light'],
};
