// What each language is called, as data/languages.json declares it.
//
// Generated by tools/gen_types.py; edit the JSON and run it again.

/// One language: its code, and what it is called in English and by its speakers.
pub struct Named {
    pub code: &'static str,
    pub english: &'static str,
    pub native: &'static str,
    pub rtl: bool,
}

pub static LANGUAGES: [Named; 29] = [
    Named {
        code: "ar",
        english: "Arabic",
        native: "العربية",
        rtl: true,
    },
    Named {
        code: "cs",
        english: "Czech",
        native: "čeština",
        rtl: false,
    },
    Named {
        code: "da",
        english: "Danish",
        native: "dansk",
        rtl: false,
    },
    Named {
        code: "de",
        english: "German",
        native: "Deutsch",
        rtl: false,
    },
    Named {
        code: "el",
        english: "Greek",
        native: "Ελληνικά",
        rtl: false,
    },
    Named {
        code: "en",
        english: "English",
        native: "English",
        rtl: false,
    },
    Named {
        code: "es",
        english: "Spanish",
        native: "español",
        rtl: false,
    },
    Named {
        code: "fa",
        english: "Persian",
        native: "فارسی",
        rtl: true,
    },
    Named {
        code: "fi",
        english: "Finnish",
        native: "suomi",
        rtl: false,
    },
    Named {
        code: "fr",
        english: "French",
        native: "français",
        rtl: false,
    },
    Named {
        code: "he",
        english: "Hebrew",
        native: "עברית",
        rtl: true,
    },
    Named {
        code: "hi",
        english: "Hindi",
        native: "हिन्दी",
        rtl: false,
    },
    Named {
        code: "hu",
        english: "Hungarian",
        native: "magyar",
        rtl: false,
    },
    Named {
        code: "id",
        english: "Indonesian",
        native: "Bahasa Indonesia",
        rtl: false,
    },
    Named {
        code: "it",
        english: "Italian",
        native: "italiano",
        rtl: false,
    },
    Named {
        code: "ja",
        english: "Japanese",
        native: "日本語",
        rtl: false,
    },
    Named {
        code: "ko",
        english: "Korean",
        native: "한국어",
        rtl: false,
    },
    Named {
        code: "nl",
        english: "Dutch",
        native: "Nederlands",
        rtl: false,
    },
    Named {
        code: "no",
        english: "Norwegian",
        native: "norsk",
        rtl: false,
    },
    Named {
        code: "pl",
        english: "Polish",
        native: "polski",
        rtl: false,
    },
    Named {
        code: "pt",
        english: "Portuguese",
        native: "português",
        rtl: false,
    },
    Named {
        code: "ro",
        english: "Romanian",
        native: "română",
        rtl: false,
    },
    Named {
        code: "ru",
        english: "Russian",
        native: "русский",
        rtl: false,
    },
    Named {
        code: "sv",
        english: "Swedish",
        native: "svenska",
        rtl: false,
    },
    Named {
        code: "th",
        english: "Thai",
        native: "ไทย",
        rtl: false,
    },
    Named {
        code: "tr",
        english: "Turkish",
        native: "Türkçe",
        rtl: false,
    },
    Named {
        code: "uk",
        english: "Ukrainian",
        native: "українська",
        rtl: false,
    },
    Named {
        code: "vi",
        english: "Vietnamese",
        native: "Tiếng Việt",
        rtl: false,
    },
    Named {
        code: "zh",
        english: "Chinese",
        native: "中文",
        rtl: false,
    },
];

/// The code a language's English name belongs to, for reading a page that heads its
/// sections with names rather than codes.
pub fn code_of(english: &str) -> Option<&'static str> {
    LANGUAGES
        .iter()
        .find(|row| row.english.eq_ignore_ascii_case(english.trim()))
        .map(|row| row.code)
}

/// What to call this language to a reader, or the code when it is not named.
pub fn english(code: &str) -> &str {
    LANGUAGES
        .iter()
        .find(|row| row.code == code)
        .map(|row| row.english)
        .unwrap_or(code)
}
