//! Which reading of a homograph the word before it makes likely.
//!
//! Generated by tools/gen_types.py from data/neighbours.json; edit that and run it
//! again. The rules are authored rather than trained, and they are the signal that
//! works in every language: a determiner is followed by a noun, an infinitive marker
//! by a verb. Where a language has a trained classifier it outranks this.

/// One rule: the part of speech before, and what it makes the word after it.
pub struct Neighbour {
    pub after: &'static str,
    pub prefers: &'static str,
}

/// How much more the preferred reading has to be worth than the runner-up before the
/// card stops offering the choice.
pub const MARGIN: u32 = 1;

pub static RULES: [Neighbour; 10] = [
    Neighbour {
        after: "det",
        prefers: "noun",
    }, // a determiner introduces a noun phrase
    Neighbour {
        after: "article",
        prefers: "noun",
    }, // the same, where the dump calls it that
    Neighbour {
        after: "adj",
        prefers: "noun",
    }, // an adjective modifies the noun after it
    Neighbour {
        after: "num",
        prefers: "noun",
    }, // a number counts something
    Neighbour {
        after: "pron",
        prefers: "verb",
    }, // a pronoun subject takes a verb
    Neighbour {
        after: "particle",
        prefers: "verb",
    }, // an infinitive marker: to book, zu buchen
    Neighbour {
        after: "aux",
        prefers: "verb",
    }, // an auxiliary takes a participle or infinitive
    Neighbour {
        after: "adv",
        prefers: "verb",
    }, // an adverb before a word modifies a verb
    Neighbour {
        after: "prep",
        prefers: "noun",
    }, // a preposition governs a noun phrase
    Neighbour {
        after: "conj",
        prefers: "verb",
    }, // a clause after a conjunction begins again
];
