package io.github.tieo.phonetix.ui

/**
 * The design tokens, as the surface page declares them.
 *
 * Generated by tools/tokens.py from docs/merge/surface.html; edit that and run it
 * again. A colour written here by hand is a colour the browser does not have, which
 * is the drift one set of tokens exists to prevent.
 *
 * Colours are ARGB, which is what Compose's Color takes. A role names what a thing is
 * for and never what colour it is, so a new theme is a new palette and nothing here
 * changes.
 */
object Tokens {

    /** Sizes, spacings and radii, which no theme changes. */
    object Scale {
        const val audioSize = 28.0f
        const val badgeHeight = 22.0f
        const val borderWidth = 1.0f
        const val breakpointPhone = 600.0f
        const val buttonHeight = 36.0f
        const val cardWidth = 360.0f
        const val diagramHeight = 72.0f
        const val diagramWidth = 96.0f
        const val fontSizeBody = 15.0f
        const val fontSizeHeadline = 22.0f
        const val fontSizeIpa = 16.0f
        const val fontSizeIpaLens = 13.0f
        const val fontSizeLabel = 11.0f
        const val fontSizeLemma = 17.0f
        const val fontSizeLens = 14.0f
        const val fontSizePage = 17.0f
        const val fontSizeSense = 14.0f
        const val fontSizeSmall = 12.0f
        const val fontSizeSymbol = 32.0f
        const val handleHeight = 4.0f
        const val handleWidth = 36.0f
        const val iconSize = 20.0f
        const val lensRing = 3.0f
        const val lensSize = 56.0f
        const val lineBody = 1.45f
        const val linePage = 1.5f
        const val markSize = 15.0f
        const val popoverWidth = 300.0f
        const val progressHeight = 6.0f
        const val radiusBar = 3.0f
        const val radiusButton = 8.0f
        const val radiusCard = 14.0f
        const val radiusChip = 999.0f
        const val radiusSymbol = 6.0f
        const val rubyInboxScale = 0.5f
        const val rubyIpaScale = 0.55f
        const val rubyScale = 0.62f
        const val skeletonHeight = 12.0f
        const val space1 = 4.0f
        const val space2 = 8.0f
        const val space3 = 12.0f
        const val space4 = 16.0f
        const val space5 = 24.0f
        const val space6 = 32.0f
        const val tierCompactMinHeight = 240.0f
        const val tierCompactMinWidth = 240.0f
        const val tierFullMinHeight = 400.0f
        const val tierFullMinWidth = 320.0f
        const val toggleHeight = 22.0f
        const val toggleWidth = 40.0f
        const val touchTarget = 44.0f
        const val weightBold = 650.0f
        const val weightMedium = 500.0f
        const val weightRegular = 400.0f
    }

    /** Which set of colours a reader has chosen. */
    enum class Theme { CLASSROOM, INK, PAPER }

    /** What each role is worth in one theme and mode. */
    data class Palette(
        val accent: Long,
        val accentBg: Long,
        val accentInk: Long,
        val border: Long,
        val chipBg: Long,
        val chipInk: Long,
        val danger: Long,
        val dangerBg: Long,
        val guess: Long,
        val guessBg: Long,
        val ink: Long,
        val inkFaint: Long,
        val inkMuted: Long,
        val ipa: Long,
        val ipaConsonant: Long,
        val ipaOther: Long,
        val ipaVowel: Long,
        val pageBg: Long,
        val rubyInk: Long,
        val rubyIpa: Long,
        val scrim: Long,
        val shadow: Long,
        val skeleton: Long,
        val surface: Long,
        val surfaceRaised: Long,
        val rubyHue: Long,
    )

    fun palette(theme: Theme, dark: Boolean): Palette = when {
        theme == Theme.CLASSROOM && !dark -> Palette(
            accent = 0xFF0F6E8CL,
            accentBg = 0xFFDFF1F6L,
            accentInk = 0xFFFFFFFFL,
            border = 0xFFDDD6C4L,
            chipBg = 0xFFEBE6D8L,
            chipInk = 0xFF3E3A33L,
            danger = 0xFFA63A2AL,
            dangerBg = 0xFFF9E6E2L,
            guess = 0xFF8A4F0CL,
            guessBg = 0xFFFBE9CFL,
            ink = 0xFF1A1A1AL,
            inkFaint = 0xFF6F6A62L,
            inkMuted = 0xFF4F4A42L,
            ipa = 0xFF1B4EA3L,
            ipaConsonant = 0xFF1B4EA3L,
            ipaOther = 0xFF5C5852L,
            ipaVowel = 0xFFB8410AL,
            pageBg = 0xFFF6F3EAL,
            rubyInk = 0xFF1B4EA3L,
            rubyIpa = 0xFF4F4A42L,
            scrim = 0x0F1E190AL,
            shadow = 0x331E190AL,
            skeleton = 0xFFE6E1D3L,
            surface = 0xFFFFFDF7L,
            surfaceRaised = 0xFFF4F0E4L,
            rubyHue = 0x00000000L,
        )
        theme == Theme.CLASSROOM && dark -> Palette(
            accent = 0xFF6FC3DDL,
            accentBg = 0xFF173640L,
            accentInk = 0xFF0C2530L,
            border = 0xFF343C45L,
            chipBg = 0xFF2C343CL,
            chipInk = 0xFFDCD8CFL,
            danger = 0xFFFF9A8AL,
            dangerBg = 0xFF3D2622L,
            guess = 0xFFF0B566L,
            guessBg = 0xFF3D2B12L,
            ink = 0xFFF2F2F2L,
            inkFaint = 0xFF948F86L,
            inkMuted = 0xFFB9B4AAL,
            ipa = 0xFF8AB4FFL,
            ipaConsonant = 0xFF8AB4FFL,
            ipaOther = 0xFFB5B0A7L,
            ipaVowel = 0xFFFFAB70L,
            pageBg = 0xFF14181CL,
            rubyInk = 0xFF8AB4FFL,
            rubyIpa = 0xFFB9B4AAL,
            scrim = 0x0FFFFFFFL,
            shadow = 0x99000000L,
            skeleton = 0xFF2C343CL,
            surface = 0xFF1B2127L,
            surfaceRaised = 0xFF232A31L,
            rubyHue = 0x00000000L,
        )
        theme == Theme.INK && !dark -> Palette(
            accent = 0xFF0028A8L,
            accentBg = 0xFFE3E8FFL,
            accentInk = 0xFFFFFFFFL,
            border = 0xFF000000L,
            chipBg = 0xFFE6E6E6L,
            chipInk = 0xFF000000L,
            danger = 0xFFA00000L,
            dangerBg = 0xFFFFE0E0L,
            guess = 0xFF6B3400L,
            guessBg = 0xFFFFE3C4L,
            ink = 0xFF000000L,
            inkFaint = 0xFF3D3D3DL,
            inkMuted = 0xFF1F1F1FL,
            ipa = 0xFF0028A8L,
            ipaConsonant = 0xFF0028A8L,
            ipaOther = 0xFF1F1F1FL,
            ipaVowel = 0xFF6B3400L,
            pageBg = 0xFFFFFFFFL,
            rubyInk = 0xFF0028A8L,
            rubyIpa = 0xFF1F1F1FL,
            scrim = 0x14000000L,
            shadow = 0x59000000L,
            skeleton = 0xFFD9D9D9L,
            surface = 0xFFFFFFFFL,
            surfaceRaised = 0xFFF2F2F2L,
            rubyHue = 0x00000000L,
        )
        theme == Theme.INK && dark -> Palette(
            accent = 0xFF9ECBFFL,
            accentBg = 0xFF10284AL,
            accentInk = 0xFF000000L,
            border = 0xFFFFFFFFL,
            chipBg = 0xFF262626L,
            chipInk = 0xFFFFFFFFL,
            danger = 0xFFFF9A8AL,
            dangerBg = 0xFF3A1410L,
            guess = 0xFFFFC36BL,
            guessBg = 0xFF3D2600L,
            ink = 0xFFFFFFFFL,
            inkFaint = 0xFFC4C4C4L,
            inkMuted = 0xFFE6E6E6L,
            ipa = 0xFF9ECBFFL,
            ipaConsonant = 0xFF9ECBFFL,
            ipaOther = 0xFFE6E6E6L,
            ipaVowel = 0xFFFFC36BL,
            pageBg = 0xFF000000L,
            rubyInk = 0xFF9ECBFFL,
            rubyIpa = 0xFFE6E6E6L,
            scrim = 0x14FFFFFFL,
            shadow = 0xCC000000L,
            skeleton = 0xFF2A2A2AL,
            surface = 0xFF000000L,
            surfaceRaised = 0xFF161616L,
            rubyHue = 0x00000000L,
        )
        theme == Theme.PAPER && !dark -> Palette(
            accent = 0xFF2F6F9FL,
            accentBg = 0xFFE7F0F7L,
            accentInk = 0xFFFFFFFFL,
            border = 0xFFE2DED5L,
            chipBg = 0xFFECE9E2L,
            chipInk = 0xFF4A463FL,
            danger = 0xFFA63A2AL,
            dangerBg = 0xFFF9E6E2L,
            guess = 0xFF8A4F0CL,
            guessBg = 0xFFFBEFDCL,
            ink = 0xFF1C1B19L,
            inkFaint = 0xFF767169L,
            inkMuted = 0xFF5E5A52L,
            ipa = 0xFF2F4F70L,
            ipaConsonant = 0xFF2F4F70L,
            ipaOther = 0xFF767169L,
            ipaVowel = 0xFF8A4B12L,
            pageBg = 0xFFF3F1ECL,
            rubyInk = 0xFF2F4F70L,
            rubyIpa = 0xFF5E5A52L,
            scrim = 0x0F14120EL,
            shadow = 0x2E14120EL,
            skeleton = 0xFFE8E5DEL,
            surface = 0xFFFFFFFFL,
            surfaceRaised = 0xFFF8F7F3L,
            rubyHue = 0x00000000L,
        )
        theme == Theme.PAPER && dark -> Palette(
            accent = 0xFF7FB3DCL,
            accentBg = 0xFF223543L,
            accentInk = 0xFF10202EL,
            border = 0xFF33363DL,
            chipBg = 0xFF30333AL,
            chipInk = 0xFFD3D0C8L,
            danger = 0xFFE58A7AL,
            dangerBg = 0xFF3D2622L,
            guess = 0xFFE0A85AL,
            guessBg = 0xFF3A2D1AL,
            ink = 0xFFECEBE6L,
            inkFaint = 0xFF8E8A82L,
            inkMuted = 0xFFAAA69DL,
            ipa = 0xFFA9C4DCL,
            ipaConsonant = 0xFFA9C4DCL,
            ipaOther = 0xFF8E8A82L,
            ipaVowel = 0xFFE0B070L,
            pageBg = 0xFF15161AL,
            rubyInk = 0xFFA9C4DCL,
            rubyIpa = 0xFFAAA69DL,
            scrim = 0x0DFFFFFFL,
            shadow = 0x8C000000L,
            skeleton = 0xFF2E3138L,
            surface = 0xFF1F2126L,
            surfaceRaised = 0xFF272A30L,
            rubyHue = 0x00000000L,
        )
        // A theme with no palette is a build that generated one and not the other.
        else -> palette(Theme.CLASSROOM, dark)
    }
}
