/**
 * Writes the cases that pin the Android port to the extension's own behaviour.
 *
 * src/lib/sprinkle.ts is the single definition of which words get transcribed and of the
 * frequency curve behind the bar. Kotlin cannot import it, so instead this emits what it
 * answers for a spread of inputs, and the port asserts itself against that file. Change the
 * rule in one place without carrying it across and the Android test fails, rather than the
 * same setting quietly meaning two different things on two devices.
 *
 *   node --experimental-strip-types scripts/gen-sprinkle-vectors.ts
 */
import { writeFileSync, mkdirSync } from 'node:fs';
import { dirname } from 'node:path';
import { picks, densityForPos, posForDensity, DENSITY_MIN, DENSITY_MAX } from '../src/lib/sprinkle.ts';

const OUT = 'shared/sprinkle-vectors.json';

// A spread of shapes rather than a word list: lengths on both sides of every bend in the
// rarity boost, repeats to exercise the occurrence gate, and non-ASCII to catch a hash that
// went through bytes instead of code units.
const WORDS = [
  'a', 'to', 'cat', 'four', 'seven', 'letter', 'reading', 'language',
  'pronounce', 'dictionary', 'pronunciation', 'internationalisation',
  'für', 'größer', 'naïve', "don't", 'ʃwa',
];
const OCCURRENCES = [0, 1, 2, 3, 7];
const DENSITIES = [DENSITY_MIN, 3, 5, 8, 12, 20, 33, DENSITY_MAX];

const pickCases: Array<{ word: string; occurrence: number; density: number; picked: boolean }> = [];
for (const word of WORDS) {
  for (const occurrence of OCCURRENCES) {
    for (const density of DENSITIES) {
      pickCases.push({ word, occurrence, density, picked: picks(word, occurrence, density) });
    }
  }
}

const curveCases: Array<{ pos: number; density: number }> = [];
for (let i = 0; i <= 100; i++) {
  const pos = i / 100;
  curveCases.push({ pos, density: densityForPos(pos) });
}

const inverseCases: Array<{ density: number; pos: number }> = [];
for (let d = DENSITY_MIN; d <= DENSITY_MAX; d++) {
  inverseCases.push({ density: d, pos: posForDensity(d) });
}

mkdirSync(dirname(OUT), { recursive: true });
writeFileSync(OUT, JSON.stringify({
  note: 'Generated by scripts/gen-sprinkle-vectors.ts from src/lib/sprinkle.ts. Do not edit.',
  densityMin: DENSITY_MIN,
  densityMax: DENSITY_MAX,
  picks: pickCases,
  curve: curveCases,
  inverse: inverseCases,
}, null, 2) + '\n');

console.log(`wrote ${OUT}: ${pickCases.length} pick cases, ${curveCases.length} curve, ${inverseCases.length} inverse`);
