/**
 * Writes the symbol table and the cases that pin the Android tooltip to the extension's.
 *
 * The names, examples and the rule for splitting a transcription into symbols live in
 * src/lib/ipa-symbols.ts and are used directly by the extension's tooltip. Kotlin cannot
 * import them, so the table is emitted here and the port reads it, and a spread of real
 * transcriptions is emitted with the tokens and descriptions the extension produces for
 * them, which IpaSymbolsParityTest asserts the port against.
 *
 *   node --experimental-strip-types scripts/gen-ipa-symbols.ts
 */
import { writeFileSync, mkdirSync, readFileSync } from 'node:fs';
import { dirname } from 'node:path';
import { gunzipSync } from 'node:zlib';
import { IPA_SYMBOLS, DIACRITICS, STANDALONE_MODIFIERS, tokenizeIPA, describeSymbol } from '../src/lib/ipa-symbols.ts';
import { displayIpa } from '../src/lib/display-ipa.ts';

const OUT = 'shared/ipa-symbols.json';

// The table itself: what the extension shows for a symbol it knows by name.
const symbols: Record<string, { name: string; example: string; type: string }> = {};
for (const [token, info] of Object.entries(IPA_SYMBOLS)) {
  symbols[token] = { name: info.name, example: info.example, type: info.type };
}

// Real transcriptions rather than invented ones: whatever the shipped dictionary actually
// says, so the cases cover the diacritics and stress marks that really occur.
const words = ['cat', 'pronunciation', 'thought', 'measure', 'singer', 'water', 'quiet',
  'church', 'judge', 'ring', 'father', 'about', 'bird', 'house', 'boy', 'view', 'few'];
let dict: Record<string, string> = {};
try {
  dict = JSON.parse(gunzipSync(readFileSync('public/dictionaries/en.json.gz')).toString('utf8'));
} catch {
  console.error('public/dictionaries/en.json.gz is missing; run `pnpm fetch:dict` first');
  process.exit(1);
}

const cases: Array<{ ipa: string; tokens: string[]; names: Array<string | null> }> = [];
for (const w of words) {
  const ipa = dict[w];
  if (!ipa) continue;
  const tokens = tokenizeIPA(ipa);
  cases.push({ ipa, tokens, names: tokens.map(t => describeSymbol(t)?.name ?? null) });
}

// Diacritics and precomposed forms exercise the part of describeSymbol that decomposes a
// symbol and re-words its description, which is the easiest place for a port to drift.
for (const ipa of ['z̥', 'ã', 'tʰ', 'd͡ʒ', 'ɫ', 'e̞', 'ɹ̩', 'kʷ']) {
  const tokens = tokenizeIPA(ipa);
  cases.push({ ipa, tokens, names: tokens.map(t => describeSymbol(t)?.name ?? null) });
}

// How the same transcription is shown in running text, which is not how the tooltip shows
// it: the tooltip carries the full form, the text is stripped to taste.
const display: Array<{ ipa: string; broad: string; narrow: string; withStress: string }> = [];
for (const c of cases) {
  display.push({
    ipa: c.ipa,
    broad: displayIpa(c.ipa, { narrow: false, hideStress: true }),
    narrow: displayIpa(c.ipa, { narrow: true, hideStress: true }),
    withStress: displayIpa(c.ipa, { narrow: false, hideStress: false }),
  });
}
for (const ipa of ['ˈtu(ː)l.tɪp', 'kʰoːz̥', 'ˌæktɪvˈeɪʃən']) {
  display.push({
    ipa,
    broad: displayIpa(ipa, { narrow: false, hideStress: true }),
    narrow: displayIpa(ipa, { narrow: true, hideStress: true }),
    withStress: displayIpa(ipa, { narrow: false, hideStress: false }),
  });
}

mkdirSync(dirname(OUT), { recursive: true });
writeFileSync(OUT, JSON.stringify({
  note: 'Generated by scripts/gen-ipa-symbols.ts from src/lib/ipa-symbols.ts. Do not edit.',
  symbols,
  // The marks a symbol can carry, and what each one is called. describeSymbol takes a
  // composed symbol apart against this table, and so must the port.
  diacritics: DIACRITICS,
  // The suprasegmentals that sit in the modifier range but are symbols in their own right
  // rather than marks on the sound before them.
  standaloneModifiers: [...STANDALONE_MODIFIERS],
  cases,
  display,
}, null, 2) + '\n');

console.log(`wrote ${OUT}: ${Object.keys(symbols).length} symbols, ${cases.length} cases`);
