"""One set of design tokens, read from the surface and written out for both platforms.

The surface page is where every colour, size, radius and spacing is declared, because it is
the thing a person looks at when deciding them. The phone cannot read a stylesheet, so the
same declarations are written out as data and as a Kotlin object, and a check says when the
three have drifted apart. Editing the page and forgetting the phone is then a failing build
rather than a card that looks wrong on one platform only.

  uv run python tools/tokens.py            # write data/tokens.json and the Kotlin object
  uv run python tools/tokens.py --check    # say whether what is written is still current
"""
import json
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
SURFACE = os.path.join(ROOT, "docs", "merge", "surface.html")
TOKENS = os.path.join(ROOT, "data", "tokens.json")
KOTLIN = os.path.join(
    ROOT, "android", "app", "src", "main", "java", "io", "github", "tieo", "phonetix",
    "ui", "Tokens.kt",
)


def blocks(css):
    """Every rule in the stylesheet, as (selector, declarations)."""
    out = []
    for match in re.finditer(r"([^{}]+)\{([^{}]*)\}", css):
        selector = match.group(1).strip().splitlines()[-1].strip()
        body = {}
        for line in match.group(2).split(";"):
            line = re.sub(r"/\*.*?\*/", "", line).strip()
            if not line.startswith("--") or ":" not in line:
                continue
            name, value = line.split(":", 1)
            body[name.strip()] = value.strip()
        if body:
            out.append((selector, body))
    return out


def read_surface():
    """The scalars, the palettes and the roles, as the page declares them."""
    with open(SURFACE) as f:
        page = f.read()
    style = "\n".join(re.findall(r"<style>(.*?)</style>", page, re.S))
    # The comments carry the reasoning and would otherwise be parsed as declarations.
    style = re.sub(r"/\*.*?\*/", "", style, flags=re.S)

    scalars, palettes, roles = {}, {}, {}
    for selector, body in blocks(style):
        if selector == ":root":
            scalars.update({k: v for k, v in body.items() if not k.startswith("--p-")})
        elif selector.startswith(".theme-"):
            match = re.match(r"\.theme-([a-z]+)\.mode-([a-z]+)", selector)
            if match:
                palettes[f"{match.group(1)}-{match.group(2)}"] = body
        elif "theme-" in selector:
            # The semantic layer: a role names a palette entry and never a colour.
            for role, value in body.items():
                seen = re.match(r"var\((--p-[a-z0-9-]+)\)", value)
                if seen:
                    roles[role] = seen.group(1)
    return scalars, palettes, roles


def as_argb(value):
    """A CSS colour as the number a phone wants, or nothing when it is not one."""
    value = value.strip()
    hexed = re.fullmatch(r"#([0-9a-fA-F]{3,8})", value)
    if hexed:
        digits = hexed.group(1)
        if len(digits) == 3:
            digits = "".join(c * 2 for c in digits)
        if len(digits) == 6:
            return 0xFF000000 | int(digits, 16)
        if len(digits) == 8:
            # CSS writes the alpha last and a phone wants it first.
            rgb, alpha = int(digits[:6], 16), int(digits[6:], 16)
            return (alpha << 24) | rgb
        return None
    rgba = re.fullmatch(r"rgba?\(([^)]+)\)", value)
    if rgba:
        parts = [p.strip() for p in rgba.group(1).replace("/", ",").split(",")]
        if len(parts) < 3:
            return None
        try:
            r, g, b = (int(float(p)) for p in parts[:3])
            alpha = float(parts[3]) if len(parts) > 3 else 1.0
        except ValueError:
            return None
        return (int(round(alpha * 255)) << 24) | (r << 16) | (g << 8) | b
    return None


def camel(name):
    parts = name.removeprefix("--").removeprefix("p-").removeprefix("color-").split("-")
    return parts[0] + "".join(p.capitalize() for p in parts[1:])


def kotlin(scalars, palettes, roles):
    """The same tokens as a Kotlin object, so a Compose card cannot invent its own."""
    themes = sorted({name.rsplit("-", 1)[0] for name in palettes})
    named = sorted(roles)
    lines = [
        "package io.github.tieo.phonetix.ui",
        "",
        "/**",
        " * The design tokens, as the surface page declares them.",
        " *",
        " * Generated by tools/tokens.py from docs/merge/surface.html; edit that and run it",
        " * again. A colour written here by hand is a colour the browser does not have, which",
        " * is the drift one set of tokens exists to prevent.",
        " *",
        " * Colours are ARGB, which is what Compose's Color takes. A role names what a thing is",
        " * for and never what colour it is, so a new theme is a new palette and nothing here",
        " * changes.",
        " */",
        "object Tokens {",
        "",
        "    /** Sizes, spacings and radii, which no theme changes. */",
        "    object Scale {",
    ]
    for name, value in sorted(scalars.items()):
        number = re.fullmatch(r"(-?[\d.]+)(px|em|rem)?", value.strip())
        if number and number.group(2) in (None, "px"):
            lines.append(f"        const val {camel(name)} = {float(number.group(1))}f")
    lines += [
        "    }",
        "",
        "    /** Which set of colours a reader has chosen. */",
        "    enum class Theme { " + ", ".join(t.upper() for t in themes) + " }",
        "",
        "    /** What each role is worth in one theme and mode. */",
        "    data class Palette(",
    ]
    for role in named:
        lines.append(f"        val {camel(role)}: Long,")
    lines += ["    )", "", "    fun palette(theme: Theme, dark: Boolean): Palette = when {"]
    for theme in themes:
        for mode in ("light", "dark"):
            key = f"{theme}-{mode}"
            if key not in palettes:
                continue
            test = f"theme == Theme.{theme.upper()} && {'dark' if mode == 'dark' else '!dark'}"
            lines.append(f"        {test} -> Palette(")
            for role in named:
                value = palettes[key].get(roles[role], "")
                argb = as_argb(value)
                lines.append(f"            {camel(role)} = 0x{argb:08X}L,"
                             if argb is not None else
                             f"            {camel(role)} = 0x00000000L,")
            lines.append("        )")
    lines += [
        "        // A theme with no palette is a build that generated one and not the other.",
        f"        else -> palette(Theme.{themes[0].upper()}, dark)",
        "    }",
        "}",
        "",
    ]
    return "\n".join(lines)


def main():
    scalars, palettes, roles = read_surface()
    if not palettes or not roles:
        print("the surface page declares no palettes or no roles; nothing to write")
        return 1
    data = {
        "note": "Generated from docs/merge/surface.html by tools/tokens.py. Edit the page.",
        "scale": scalars,
        "roles": roles,
        "palettes": palettes,
    }
    written = json.dumps(data, indent=2, ensure_ascii=False, sort_keys=True) + "\n"
    code = kotlin(scalars, palettes, roles)

    if "--check" in sys.argv:
        stale = []
        for path, want in ((TOKENS, written), (KOTLIN, code)):
            have = open(path).read() if os.path.exists(path) else None
            if have != want:
                stale.append(os.path.relpath(path, ROOT))
        if stale:
            print("out of date with the surface page: " + ", ".join(stale))
            print("run: uv run python tools/tokens.py")
            return 1
        print(f"{len(palettes)} palettes and {len(roles)} roles, and both platforms have them")
        return 0

    os.makedirs(os.path.dirname(TOKENS), exist_ok=True)
    with open(TOKENS, "w") as f:
        f.write(written)
    os.makedirs(os.path.dirname(KOTLIN), exist_ok=True)
    with open(KOTLIN, "w") as f:
        f.write(code)
    print(f"{len(palettes)} palettes, {len(roles)} roles, {len(scalars)} scalars")
    print(f"wrote {os.path.relpath(TOKENS, ROOT)} and {os.path.relpath(KOTLIN, ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
