// The accents each language offers.
//
// Generated by tools/gen_types.py from data/accents.json; edit that and run it
// again. An accent is offered only where there is a voice that really exists or a
// rule that holds for a whole vocabulary.

export interface Accent {
  id: string;
  name: string;
  /** The espeak voice, which is what says a word nothing has a recording of. */
  voice: string;
  /** Whether the core rewrites a standard transcription into this accent. */
  rule: boolean;
}

export const ACCENTS: Record<string, Accent[]> = {
  de: [{ id: "de", name: "Germany", voice: "de", rule: false }, { id: "de-ch", name: "Switzerland", voice: "de", rule: true }, { id: "de-at", name: "Austria", voice: "de", rule: true }],
  en: [{ id: "en-gb", name: "British", voice: "en-gb-x-rp", rule: false }, { id: "en-us", name: "American", voice: "en-us", rule: true }, { id: "en-gb-scotland", name: "Scottish", voice: "en-gb-scotland", rule: false }, { id: "en-au", name: "Australian", voice: "en-au", rule: false }, { id: "en-029", name: "Caribbean", voice: "en-029", rule: false }, { id: "en-ca", name: "Canadian", voice: "en-us", rule: true }],
  es: [{ id: "es", name: "Spain", voice: "es", rule: false }, { id: "es-419", name: "Latin America", voice: "es-419", rule: true }, { id: "es-ar", name: "Rioplatense", voice: "es-419", rule: true }],
  fr: [{ id: "fr", name: "France", voice: "fr", rule: false }, { id: "fr-ca", name: "Canada", voice: "fr-ca", rule: false }],
  pt: [{ id: "pt", name: "Portugal", voice: "pt", rule: false }, { id: "pt-br", name: "Brazil", voice: "pt-br", rule: false }],
  vi: [{ id: "vi", name: "Northern", voice: "vi", rule: false }, { id: "vi-vn-x-central", name: "Central", voice: "vi-vn-x-central", rule: false }],
};

/** What a language offers, which is nothing for most of them. */
export function accentsOf(lang: string): Accent[] {
  return ACCENTS[lang] ?? [];
}

/** The voice that says a word in this accent, or the language's own. */
export function voiceOf(lang: string, accent: string): string {
  return accentsOf(lang).find((row) => row.id === accent)?.voice ?? lang;
}
