// What each language is called.
//
// Generated by tools/gen_types.py from data/languages.json; edit that and run it
// again. A code the table does not hold is shown as the code: inventing a name for a
// language is worse than admitting the table is short.

export interface Named {
  english: string;
  /** What a speaker of it calls it. */
  native: string;
  rtl: boolean;
}

export const LANGUAGES: Record<string, Named> = {
  ar: { english: "Arabic", native: "العربية", rtl: true },
  cs: { english: "Czech", native: "čeština", rtl: false },
  da: { english: "Danish", native: "dansk", rtl: false },
  de: { english: "German", native: "Deutsch", rtl: false },
  el: { english: "Greek", native: "Ελληνικά", rtl: false },
  en: { english: "English", native: "English", rtl: false },
  es: { english: "Spanish", native: "español", rtl: false },
  fa: { english: "Persian", native: "فارسی", rtl: true },
  fi: { english: "Finnish", native: "suomi", rtl: false },
  fr: { english: "French", native: "français", rtl: false },
  he: { english: "Hebrew", native: "עברית", rtl: true },
  hi: { english: "Hindi", native: "हिन्दी", rtl: false },
  hu: { english: "Hungarian", native: "magyar", rtl: false },
  id: { english: "Indonesian", native: "Bahasa Indonesia", rtl: false },
  it: { english: "Italian", native: "italiano", rtl: false },
  ja: { english: "Japanese", native: "日本語", rtl: false },
  ko: { english: "Korean", native: "한국어", rtl: false },
  nl: { english: "Dutch", native: "Nederlands", rtl: false },
  no: { english: "Norwegian", native: "norsk", rtl: false },
  pl: { english: "Polish", native: "polski", rtl: false },
  pt: { english: "Portuguese", native: "português", rtl: false },
  ro: { english: "Romanian", native: "română", rtl: false },
  ru: { english: "Russian", native: "русский", rtl: false },
  sv: { english: "Swedish", native: "svenska", rtl: false },
  th: { english: "Thai", native: "ไทย", rtl: false },
  tr: { english: "Turkish", native: "Türkçe", rtl: false },
  uk: { english: "Ukrainian", native: "українська", rtl: false },
  vi: { english: "Vietnamese", native: "Tiếng Việt", rtl: false },
  zh: { english: "Chinese", native: "中文", rtl: false },
};

/** What to call this language to a reader, or the code when it is not named. */
export function named(code: string): string {
  return LANGUAGES[code]?.english ?? code;
}
