// The words the settings surfaces are made of.
//
// Generated by tools/gen_types.py from data/wording.json; edit that and run it again.
// A choice a surface cannot draw is not offered on it: a browser owns the page and can
// make room above a line, an overlay on a phone can only paint over what is already
// there, so the phone has no "both" and no separate "in place" - its chip is the
// replacement. The table says which platform each choice is for.
// Both platforms say them: a row named one thing here and another on the phone is one
// product speaking with two voices, and a one-word label is only a choice for somebody
// who already knows what the other options are.

export interface Choice {
  /** What the setting is stored as. */
  value: string;
  /** What it is called on screen. */
  label: string;
  /** What it does, in one line. */
  about: string;
}

/** What one row is called, and what it says under its name. */
export interface Words {
  name: string;
  about: string;
}

/** Light or dark, as a browser can draw them. */
export const DARK_CHOICES: Choice[] = [
  { value: "system", label: "System", about: "whatever this device is set to" },
  { value: "light", label: "Light", about: "always the light side of the palette" },
  { value: "dark", label: "Dark", about: "always the dark side of the palette" },
];

/** Transcriptions, as a browser can draw them. */
export const DETAIL_CHOICES: Choice[] = [
  { value: "broad", label: "/ /", about: "the sounds that tell words apart" },
  { value: "narrow", label: "[ ]", about: "every detail of how it is said, like aspiration and devoicing" },
];

/** Overlay, as a browser can draw them. */
export const LAYER_CHOICES: Choice[] = [
  { value: "off", label: "Off", about: "nothing is replaced; ask about a word yourself" },
  { value: "meaning", label: "Translation", about: "the word replaced by what it means" },
  { value: "sound", label: "Pronunciation", about: "the word replaced by how it is said" },
  { value: "both", label: "Both", about: "what it means, and how to say that" },
];

/** Which side, as a browser can draw them. */
export const SIDE_CHOICES: Choice[] = [
  { value: "left", label: "Left", about: "for a phone held in the left hand" },
  { value: "free", label: "Anywhere", about: "it stays wherever you put it down" },
  { value: "right", label: "Right", about: "for a phone held in the right hand" },
];

/** Every row of the settings surfaces, by the name it reports itself under. */
export const ROWS: Record<string, Words> = {
  "accent": { name: "Accent", about: "" },
  "advanced": { name: "Advanced", about: "" },
  "animations": { name: "Animations", about: "" },
  "apps": { name: "Apps", about: "" },
  "dark": { name: "Light or dark", about: "" },
  "delay": { name: "Rest before a card opens", about: "" },
  "density": { name: "How often", about: "" },
  "dictionaries": { name: "Dictionaries", about: "" },
  "ipa": { name: "Pronunciation", about: "" },
  "layer": { name: "Overlay", about: "" },
  "lens-drag": { name: "Drag it over a word", about: "It says what it passes over, and the page under it still scrolls" },
  "lens-hold": { name: "Hold it", about: "Turns the overlay off, and on again; the button wears the accent colour while the overlay is on" },
  "lens-sweep": { name: "Hold it, then sweep", about: "Every word it passes over joins the run, and the card answers the whole clause" },
  "lens-tap": { name: "Tap it", about: "Ask for the word for something, in the middle of what you are reading; tap it again to put the card away" },
  "meanings": { name: "To see what a word means", about: "" },
  "narrow": { name: "Transcriptions", about: "" },
  "on": { name: "Annotate what I read", about: "" },
  "rest": { name: "Where the button sits", about: "" },
  "rest-pin": { name: "Pin", about: "" },
  "say": { name: "The word for something", about: "" },
  "setup": { name: "Setup", about: "" },
  "setup-overlay": { name: "Drawing over apps", about: "" },
  "setup-reading": { name: "Reading the screen", about: "" },
  "side": { name: "Which side", about: "" },
  "site": { name: "On this site", about: "" },
  "source": { name: "This page is in", about: "" },
  "start": { name: "Before it can answer a word", about: "" },
  "stress": { name: "Stress marks", about: "" },
  "target": { name: "Language", about: "" },
  "theme": { name: "Theme", about: "" },
  "touch": { name: "Touching a word", about: "" },
  "touch-words": { name: "Tap a word for its card", about: "" },
  "translate": { name: "Translation", about: "" },
  "where": { name: "Where", about: "" },
};

/** What the two ends of a bar mean. */
export const ENDS: Record<string, [string, string]> = {
  "delay": ["instant", "1000 ms"],
  "density": ["a few words", "every word"],
};

/** Phrases both surfaces use, so neither invents its own wording. */
export const SAYS: Record<string, string> = {
  "allow": "Allow",
  "allow-overlay": "Allow overlay",
  "already-in": "This page is already in %s",
  "broad-mark": "/ /",
  "change": "Change",
  "choose-language": "Choose a language",
  "close": "Close",
  "detail-explained": "Broad is the sounds that tell words apart; narrow is every detail of how one is said, as a speaker of that accent says it.",
  "dictionary-accent": "as the dictionary gives it",
  "every-app": "Every app",
  "get": "Get",
  "loading-dictionary": "Loading the dictionary…",
  "master-idle": "Nothing is drawn over your apps",
  "master-off": "Paused",
  "master-on": "Reading",
  "master-unready": "Allow it to read the screen and draw over your apps",
  "master-working": "The words in your apps are being answered",
  "narrow-mark": "[ ]",
  "no-direction": "No dictionary here for %s, so words cannot be turned into it. The words show how they sound instead.",
  "no-source": "for what a word means; how it is said is built in",
  "no-translation": "Don't translate",
  "nothing-found": "Nothing by that name",
  "nothing-yet": "nothing yet",
  "open-accessibility": "Open accessibility",
  "preview": "Preview",
  "preview-about": "the words on a page this would answer",
  "remove": "Remove",
  "replacing-off": "Overlay off",
  "replacing-on": "Overlay on",
  "rest-edge": "On the %s",
  "rest-loose": "Wherever you leave it",
  "rest-put": "Drag the button up or down, or across to the other side.",
  "say-fetching": "getting %s",
  "say-into": "Answer in",
  "say-no-language": "Choose a language to read into first.",
  "say-no-model": "No translation model for that direction at your dictionary host.",
  "say-nothing": "no word for that",
  "say-placeholder": "what you want to say",
  "search": "Search",
  "service-stopped": "Phonetix is allowed to read the screen but is not running. Switch it off and on again in the phone's accessibility settings.",
  "start-done": "done",
  "start-go": "Set this",
  "start-pack": "Get a dictionary for the language you are reading",
  "start-permission": "Let it read the screen, and draw over it",
  "start-target": "Choose the language you read into",
  "touch-off": "Every touch goes to the app underneath, so scrolling is untouched.",
  "touch-on": "A swipe that starts on a word will not scroll the page.",
  "use-this": "Use this",
};

/** What one of them is called, for a row that says what it is set to. */
export function labelOf(choices: Choice[], value: string): string {
  return choices.find((row) => row.value === value)?.label ?? value;
}

/** What one of them does, for a row that explains itself. */
export function aboutOf(choices: Choice[], value: string): string {
  return choices.find((row) => row.value === value)?.about ?? '';
}
