// The words the settings surfaces are made of.
//
// Generated by tools/gen_types.py from data/wording.json; edit that and run it again.
// A choice a surface cannot draw is not offered on it: a browser owns the page and can
// make room above a line, an overlay on a phone can only paint over what is already
// there, so the phone has no "both" and no separate "in place" - its chip is the
// replacement. The table says which platform each choice is for.
// Both platforms say them: a row named one thing here and another on the phone is one
// product speaking with two voices, and a one-word label is only a choice for somebody
// who already knows what the other options are.

export interface Choice {
  /** What the setting is stored as. */
  value: string;
  /** What it is called on screen. */
  label: string;
  /** What it does, in one line. */
  about: string;
}

/** What one row is called, and what it says under its name. */
export interface Words {
  name: string;
  about: string;
}

/** Transcriptions, as a browser can draw them. */
export const DETAIL_CHOICES: Choice[] = [
  { value: "broad", label: "Broad", about: "the sounds that tell words apart" },
  { value: "narrow", label: "Narrow", about: "every detail of how it is said, like aspiration and devoicing" },
];

/** Show over a word, as a browser can draw them. */
export const LAYER_CHOICES: Choice[] = [
  { value: "off", label: "Nothing", about: "the page as it is; a card when you stop on a word" },
  { value: "gloss", label: "What it means", about: "the meaning, above the word" },
  { value: "ipa", label: "How it is said", about: "the pronunciation, above the word" },
  { value: "gloss+ipa", label: "Both", about: "the meaning and the pronunciation, above the word" },
  { value: "replace", label: "In place of the word", about: "the word itself swapped for what it means; rest on it to see the word" },
];

/** Every row of the settings surfaces, by the name it reports itself under. */
export const ROWS: Record<string, Words> = {
  "accent": { name: "Accent", about: "which accent each language is read in" },
  "animations": { name: "Animations", about: "the card eases in; off is instant" },
  "delay": { name: "Rest before a card opens", about: "how long the cursor stays on a word before it answers" },
  "density": { name: "How often", about: "how much of the page is annotated" },
  "dictionaries": { name: "Dictionaries", about: "the words this can answer without asking anyone" },
  "host": { name: "Where they come from", about: "Fetched once and kept on this machine, so a dictionary works on a train." },
  "layer": { name: "Show over a word", about: "" },
  "more": { name: "How it reads", about: "transcriptions, stress, how long a rest opens a card" },
  "narrow": { name: "Transcriptions", about: "" },
  "on": { name: "Annotate what I read", about: "" },
  "site": { name: "On this site", about: "the default is what happens on sites you have not decided about" },
  "source": { name: "This page is in", about: "Each block is read on its own, so a page in two languages already reads correctly. Set this only where that goes wrong." },
  "stress": { name: "Stress marks", about: "over a word; the card always shows them" },
  "target": { name: "I read into", about: "the language the answers come in" },
};

/** What the two ends of a bar mean. */
export const ENDS: Record<string, [string, string]> = {
  "delay": ["instant", "1000 ms"],
  "density": ["a few words", "every word"],
};

/** Phrases both surfaces use, so neither invents its own wording. */
export const SAYS: Record<string, string> = {
  "dictionary-accent": "as the dictionary gives it",
  "no-host": "Nothing is fetched until this is set.",
  "no-source": "no source for them yet",
  "nothing-yet": "nothing yet",
};

/** What one of them is called, for a row that says what it is set to. */
export function labelOf(choices: Choice[], value: string): string {
  return choices.find((row) => row.value === value)?.label ?? value;
}

/** What one of them does, for a row that explains itself. */
export function aboutOf(choices: Choice[], value: string): string {
  return choices.find((row) => row.value === value)?.about ?? '';
}
